version: "3"

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    env_file: .env
    build: 
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_HOST: ${DB_HOST}
    image: mariadb:inception
    container_name: mariadb
    networks:
      - my_network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aouni/data/wp_data
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aouni/data/db_data

networks:
  my_network:
    name: my_network
    driver: bridge